### ISSUE TITLE
Contained Fluids Array not displaying labels correctly?

### ISSUE THREAD

**Issue by ofseaandstars** [BrisingrAerowing/TinkersOCDrivers#1]
_Forgive me, as this is probably me writing my code incorrectly._ 

----

I am attempting to read each of the contained fluids within the `.getContainedFluids()` function and print them with their labels.

My code currently goes through a loop (18 being the current max space in the smeltery):

```lua
    for i=i,18 do
        invFluids = component.smeltery.getContainedFluids()
        print(invFluids[i].label)
    end
```

What I would expect to happen is that `invFluids[i].label` would be each array's label (such as `Molten Iron`, `Molten Gold` etc etc). 
What actually happens is that it returns `Molten Iron` 18 times.

The array structure seems to be:

```lua
    {
	{
		amount=5184,
		hasTag=false,
		label="Molten Iron",
		name="iron"
	}
	{
		amount=5184,
		hasTag=false,
		label="Molten Gold",
		name="gold"
	}
    }
```

I have no idea if LUA can interpret no comma between arrays or if that doesn't matter.

If you have any idea of  how I could get each one to display that would be great.

**Comment by brisingraerowing** [comment]
Try this code:

```lua
  for _, fluid in pairs(component.smeltery.getContainedFluids()) do
    print(fluid.label)
  end
```

You may also want to sign up on [the OpenComputers forums](https://oc.cil.li/), if you aren't already. I'm relatively active there, and there are a number of other people who can help. 

EDIT: Forgot something.

**Comment by ofseaandstars** [comment]
Alright, I'll try that out when I get the chance later. Also, off topic - I left a comment on the mod's page about a logo I made for you, just in case you're interested :)

**Comment by brisingraerowing** [comment]
I'll go take a look.

**Comment by brisingraerowing** [comment]
Thanks for the logo! It is very cool!

**Comment by ofseaandstars** [comment]
No problem! A useful mod like this deserves a nice logo! If you need any more logos for any other projects, let me know.

**Comment by ofseaandstars** [comment]
I'll close this and ask for help on the forums when I need it :) Thanks for your help so far :)

**Comment by brisingraerowing** [comment]
No problem.

**Comment by pixelclef** [comment]
For my fellow coders:
```
local component = require("component")
local smeltery = component.smeltery
local fluids = {smeltery.getContainedFluids()}

for _, fluid in ipairs(fluids) do
  print(fluid.label)
end
```
