### ISSUE TITLE
getFuelInfo() and getFuelLevel() presumably not working

### ISSUE THREAD

**Issue by poxX01** [BrisingrAerowing/TinkersOCDrivers#2]
Both smeltery.getFuelInfo() and smeltery.getFuelLevel() aren't returning anything. I encounter this error exclusively on an external server, whereas in singleplayer hosted worlds the functions are doing just fine.

![javaw_2018-11-28_15-34-28](https://user-images.githubusercontent.com/23555150/49158808-562d1480-f323-11e8-8bbf-206d1fbd0f6f.png)

**Comment by brisingraerowing** [comment]
Fixed and uploaded. May take a bit to be approved (and sync to the Twitch app).

EDIT: The file was approved much faster than I expected. May still take a bit to sync to Twitch.
