### ISSUE TITLE
moveFluidToBottom not working

### ISSUE THREAD

**Issue by ComputerErika** [BrisingrAerowing/TinkersOCDrivers#4]
In the tinkers tank component, when I call moveFluidToBottom the fluid does not move to the bottom
I only have two fluids in there, gold and iron, and tried entering index 1, 2 but neither moved the fluid,
I also tried 0 and 3 but as it probably should it told me index out of bounds

**Comment by brisingraerowing** [comment]
I just tested and could not reproduce. Fluids moved around perfectly fine for me.

**Comment by brisingraerowing** [comment]
OK, further testing shows that the issue is inconsistent. I think this is a bug with Tinkers itself.

**Comment by brisingraerowing** [comment]
Some fluids work first method call, some require several calls. The number of calls seems to depend on the types of fluids and how many fluids there are. I don't think there's anything I can do with this.
